version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=booking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    restart: always

  web:
    build: .
    command: >
      bash -c "python manage.py wait_for_db &&
               python manage.py init_db &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn booking.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  celery:
    build: .
    command: celery -A booking worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: